"""
Docker deployment wizard for ForgeRAG.

Guides the user through Docker Compose configuration, generates
docker/config.yaml and .env, and optionally starts the stack.

Usage:
    python scripts/docker_setup.py              # interactive wizard
    python scripts/docker_setup.py --quick      # accept all defaults
"""

from __future__ import annotations

import argparse
import os
import secrets
import subprocess
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
_DOCKER_DIR = _ROOT / "docker"
_ENV_FILE = _ROOT / ".env"


# ---------------------------------------------------------------------------
# Pretty printing
# ---------------------------------------------------------------------------


def _is_tty() -> bool:
    return sys.stdout.isatty()


def _c(text: str, color: str) -> str:
    if not _is_tty():
        return str(text)
    codes = {
        "bold": "1",
        "dim": "2",
        "green": "32",
        "yellow": "33",
        "blue": "34",
        "cyan": "36",
        "red": "31",
    }
    return f"\033[{codes.get(color, '0')}m{text}\033[0m"


def banner(title: str):
    print()
    print(_c("━" * 60, "dim"))
    print(_c(f" {title}", "bold"))
    print(_c("━" * 60, "dim"))


def section(title: str):
    print()
    print(_c(f"▸ {title}", "cyan"))


def info(msg: str):
    print(f"  {msg}")


def success(msg: str):
    print(_c(f"  ✓ {msg}", "green"))


def warn(msg: str):
    print(_c(f"  ⚠ {msg}", "yellow"))


# ---------------------------------------------------------------------------
# Prompt helpers
# ---------------------------------------------------------------------------


class Aborted(Exception):
    pass


def ask(question: str, default: str | None = None) -> str:
    suffix = f" [{_c(default, 'yellow')}]" if default else ""
    while True:
        try:
            raw = input(f"  {question}{suffix}: ").strip()
        except (EOFError, KeyboardInterrupt):
            raise Aborted()
        val = raw or default
        if val:
            return val
        print(_c("  (required)", "red"))


def ask_bool(question: str, default: bool = False) -> bool:
    tip = "Y/n" if default else "y/N"
    while True:
        try:
            raw = input(f"  {question} [{_c(tip, 'yellow')}]: ").strip().lower()
        except (EOFError, KeyboardInterrupt):
            raise Aborted()
        if not raw:
            return default
        if raw in ("y", "yes"):
            return True
        if raw in ("n", "no"):
            return False


def ask_choice(question: str, options: list[tuple[str, str]], default: str | None = None) -> str:
    print(f"  {question}")
    default_idx = None
    for i, (val, desc) in enumerate(options, 1):
        marker = _c(" (default)", "dim") if val == default else ""
        print(f"    {i}) {_c(val, 'bold')}  {_c('— ' + desc, 'dim')}{marker}")
        if val == default:
            default_idx = i
    while True:
        try:
            default_hint = " [" + _c(str(default_idx), "yellow") + "]" if default_idx else ""
            raw = input(f"  enter [1-{len(options)}]{default_hint}: ").strip()
        except (EOFError, KeyboardInterrupt):
            raise Aborted()
        if not raw and default_idx:
            return options[default_idx - 1][0]
        if raw.isdigit() and 1 <= int(raw) <= len(options):
            return options[int(raw) - 1][0]


# ---------------------------------------------------------------------------
# Config generation
# ---------------------------------------------------------------------------


def generate_config(opts: dict) -> str:
    """Generate docker/config.yaml content."""
    lines = [
        "# Generated by docker_setup.py",
        "# Postgres + pgvector deployment",
        "",
        "persistence:",
        "  relational:",
        "    backend: postgres",
        "    postgres:",
        "      host: postgres",
        "      port: 5432",
        "      database: opencraig",
        "      user: opencraig",
        "      password_env: POSTGRES_PASSWORD",
        "  vector:",
        "    backend: pgvector",
        "    pgvector:",
        f"      dimension: {opts['dimension']}",
        "      distance: cosine",
        "      index_type: hnsw",
        "",
        "storage:",
        "  mode: local",
        "  local:",
        "    root: /app/storage/blobs",
        "",
        "embedder:",
        "  backend: litellm",
        f"  dimension: {opts['dimension']}",
        "  litellm:",
        f"    model: {opts['embed_model']}",
        f"    api_key_env: {opts['api_key_env']}",
    ]

    if opts.get("api_base"):
        lines.append(f"    api_base: {opts['api_base']}")

    lines += [
        "",
        "answering:",
        "  generator:",
        "    backend: litellm",
        f"    model: {opts['chat_model']}",
        f"    api_key_env: {opts['api_key_env']}",
    ]

    if opts.get("api_base"):
        lines.append(f"    api_base: {opts['api_base']}")

    if opts.get("neo4j"):
        lines += [
            "",
            "graph:",
            "  backend: neo4j",
            "  neo4j:",
            "    uri: bolt://neo4j:7687",
            "    user: neo4j",
            "    password_env: NEO4J_PASSWORD",
        ]

    if opts.get("kg_extraction"):
        lines += [
            "",
            "retrieval:",
            "  kg_extraction:",
            "    enabled: true",
            f"    model: {opts['chat_model']}",
            f"    api_key_env: {opts['api_key_env']}",
            "  kg_path:",
            "    enabled: true",
            f"    model: {opts['chat_model']}",
            f"    api_key_env: {opts['api_key_env']}",
        ]

    lines.append("")
    return "\n".join(lines)


def generate_env(opts: dict) -> str:
    """Generate .env content."""
    lines = [
        "# Generated by docker_setup.py",
        f"{opts['api_key_env']}={opts['api_key_value']}",
        f"POSTGRES_PASSWORD={opts['pg_password']}",
    ]
    if opts.get("neo4j"):
        lines.append(f"NEO4J_PASSWORD={opts['neo4j_password']}")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Presets
# ---------------------------------------------------------------------------

_PROVIDER_PRESETS = {
    "openai": {
        "api_key_env": "OPENAI_API_KEY",
        "embed_model": "openai/text-embedding-3-small",
        "chat_model": "openai/gpt-4o-mini",
        "dimension": 1536,
        "api_base": None,
    },
    "deepseek": {
        "api_key_env": "DEEPSEEK_API_KEY",
        "embed_model": "deepseek/deepseek-embedding",
        "chat_model": "deepseek/deepseek-chat",
        "dimension": 1536,
        "api_base": None,
    },
    "ollama": {
        "api_key_env": "OLLAMA_API_KEY",
        "embed_model": "ollama/bge-m3",
        "chat_model": "ollama/qwen2.5",
        "dimension": 1024,
        "api_base": "http://host.docker.internal:11434",
    },
    "custom": None,
}


# ---------------------------------------------------------------------------
# Main wizard
# ---------------------------------------------------------------------------


def run_wizard(quick: bool = False):
    banner("ForgeRAG Docker Setup")
    info("This wizard will configure Docker Compose for ForgeRAG.")
    info("It generates docker/config.yaml and .env, then optionally starts the stack.")

    opts: dict = {}

    # ── LLM Provider ──
    section("LLM Provider")
    if quick:
        provider = "openai"
    else:
        provider = ask_choice(
            "Which LLM provider?",
            [
                ("openai", "OpenAI (GPT-4o-mini, text-embedding-3-small)"),
                ("deepseek", "DeepSeek (deepseek-chat, deepseek-embedding)"),
                ("ollama", "Ollama local (requires Ollama running on host)"),
                ("custom", "Custom (enter model strings manually)"),
            ],
            default="openai",
        )

    if provider != "custom":
        preset = _PROVIDER_PRESETS[provider]
        opts.update(preset)
        info(f"  Chat model:  {_c(opts['chat_model'], 'bold')}")
        info(f"  Embed model: {_c(opts['embed_model'], 'bold')}")
        info(f"  Dimension:   {_c(str(opts['dimension']), 'bold')}")
    else:
        opts["api_key_env"] = ask("API key env var name", "OPENAI_API_KEY")
        opts["chat_model"] = ask("Chat model (litellm format)", "openai/gpt-4o-mini")
        opts["embed_model"] = ask("Embedding model", "openai/text-embedding-3-small")
        opts["dimension"] = int(ask("Embedding dimension", "1536"))
        opts["api_base"] = ask("API base URL (leave empty for default)", "") or None

    # API key value
    section("API Key")
    if provider == "ollama":
        opts["api_key_value"] = "ollama"
        info("Ollama doesn't need an API key, using placeholder.")
    elif quick:
        existing = os.environ.get(opts["api_key_env"], "")
        if existing:
            opts["api_key_value"] = existing
            success(f"Found {opts['api_key_env']} in environment.")
        else:
            opts["api_key_value"] = ask(f"Enter your {opts['api_key_env']}")
    else:
        existing = os.environ.get(opts["api_key_env"], "")
        if existing:
            use_existing = ask_bool(f"Found {opts['api_key_env']} in environment. Use it?", True)
            if use_existing:
                opts["api_key_value"] = existing
            else:
                opts["api_key_value"] = ask(f"Enter your {opts['api_key_env']}")
        else:
            opts["api_key_value"] = ask(f"Enter your {opts['api_key_env']}")

    # ── Passwords ──
    section("Database Passwords")
    if quick:
        opts["pg_password"] = secrets.token_urlsafe(16)
        info("Generated Postgres password.")
    else:
        opts["pg_password"] = ask("Postgres password", secrets.token_urlsafe(16))

    # ── Neo4j ──
    section("Knowledge Graph")
    if quick:
        opts["neo4j"] = False
    else:
        opts["neo4j"] = ask_bool("Enable Neo4j for knowledge graph? (adds a Neo4j container)", False)

    if opts["neo4j"]:
        if quick:
            opts["neo4j_password"] = secrets.token_urlsafe(16)
        else:
            opts["neo4j_password"] = ask("Neo4j password", secrets.token_urlsafe(16))
        opts["kg_extraction"] = ask_bool("Enable KG extraction during ingestion?", True)
    else:
        opts["kg_extraction"] = False

    # ── Write files ──
    section("Writing configuration")

    _DOCKER_DIR.mkdir(exist_ok=True)
    config_path = _DOCKER_DIR / "config.yaml"
    config_content = generate_config(opts)
    config_path.write_text(config_content, encoding="utf-8")
    success("docker/config.yaml")

    env_content = generate_env(opts)
    _ENV_FILE.write_text(env_content, encoding="utf-8")
    success(".env")

    # ── Summary ──
    banner("Ready to launch")

    compose_cmd = "docker compose up -d"
    if opts.get("neo4j"):
        compose_cmd = "docker compose --profile neo4j up -d"

    info(f"Provider:  {_c(provider, 'bold')}")
    info(f"Chat:      {_c(opts['chat_model'], 'bold')}")
    info(f"Embed:     {_c(opts['embed_model'], 'bold')}")
    info(f"Neo4j:     {_c('yes' if opts.get('neo4j') else 'no', 'bold')}")
    print()
    info("To start ForgeRAG:")
    print()
    print(f"    {_c(compose_cmd, 'green')}")
    print()
    info(f"Then open {_c('http://localhost:8000', 'cyan')}")
    print()

    if not quick:
        if ask_bool("Start now?", True):
            print()
            info("Starting Docker Compose...")
            print()
            subprocess.run(compose_cmd.split(), cwd=str(_ROOT))


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main():
    parser = argparse.ArgumentParser(description="ForgeRAG Docker setup wizard")
    parser.add_argument("--quick", action="store_true", help="Accept all defaults (OpenAI, no Neo4j)")
    args = parser.parse_args()

    try:
        run_wizard(quick=args.quick)
    except Aborted:
        print()
        print(_c("  Aborted.", "dim"))
        sys.exit(1)


if __name__ == "__main__":
    main()
